/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_maotou_bsdiff_BsDiffUtil */

#ifndef _Included_com_maotou_bsdiff_BsDiffUtil
#define _Included_com_maotou_bsdiff_BsDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maotou_bsdiff_BsDiffUtil
 * Method:    bsDiffFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_maotou_bsdiff_BsDiffUtil_bsDiffFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
